services:
  app:
    build:
      context: .
      dockerfile: docker/8.3/Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/8.3/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.nginx.rule=Host(`paris-caretaker-services.store`) || Host(`www.paris-caretaker-services.store`) || Host(`admin.paris-caretaker-services.store`)  || Host(`prestataire.paris-caretaker-services.store`)       
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: OnVaValider2024
      MYSQL_DATABASE: PCS
      MYSQL_USER: francois
      MYSQL_PASSWORD: OnVaValider2024
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=raygsm2001@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
